# Generated by Django 5.1.3 on 2024-11-28 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='message_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_answers', to='issue_module.answer'),
        ),
    ]
