# Generated by Django 5.0.6 on 2024-11-29 11:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workspace_module", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skill",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
