# Generated by Django 5.0.6 on 2024-12-12 12:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workspace_module", "0004_alter_task_rate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="created_at",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="task",
            name="updated_at",
            field=models.DateTimeField(),
        ),
    ]
