# Generated by Django 5.0.6 on 2024-12-12 10:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "workspace_module",
            "0003_alter_role_project_alter_role_skill_alter_role_user",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="rate",
            field=models.SmallIntegerField(
                blank=True,
                default=0,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
    ]
