# Generated by Django 5.0.6 on 2024-12-14 07:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workspace_module", "0005_alter_task_created_at_alter_task_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
