# Generated by Django 5.1.3 on 2024-11-28 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_module', '0004_alter_answer_assigned_attached_alter_answer_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'باز'), (2, 'بسته')], default=1),
        ),
    ]
